collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3064516
  brandStrength: 0.6738351
  lightness: 0.2992831
  brandColors:
    - '#FFFFFF'
    - '#020202'
    - '#537716'
    - '#CECFCF'
    - '#9AFF01'
  rhythmicContrast: 0
typography_spectrum: 0.7831541
layout_spectrum: 0.8978494
name: NEON
