collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6236559
  brandStrength: 0.9553308
  lightness: 0.5860215
  brandColors:
    - '#FFFFFF'
    - '#020202'
    - '#537716'
    - '#CECFCF'
    - '#9AFF01'
  rhythmicContrast: 0.2473118
typography_spectrum: 0.7831541
layout_spectrum: 0.09387079
name: NEON
